# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IronMan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IronManUI(object):
    def setupUi(self, IronManUI):
        IronManUI.setObjectName("IronManUI")
        IronManUI.resize(1900, 950)
        self.centralwidget = QtWidgets.QWidget(IronManUI)
        self.centralwidget.setObjectName("centralwidget")
        self.BG = QtWidgets.QLabel(self.centralwidget)
        self.BG.setGeometry(QtCore.QRect(-10, -10, 1950, 1000))
        self.BG.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.BG.setText("")
        self.BG.setObjectName("BG")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(10, 10, 620, 300))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("GUI-Gif/FullBodyScan.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(640, 10, 620, 430))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("GUI-Gif/Scan.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(1270, 10, 620, 300))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("GUI-Gif/World.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(10, 320, 620, 300))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("GUI-Gif/Face.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.Gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_5.setGeometry(QtCore.QRect(1270, 320, 620, 300))
        self.Gif_5.setText("")
        self.Gif_5.setPixmap(QtGui.QPixmap("GUI-Gif/Search.gif"))
        self.Gif_5.setScaledContents(True)
        self.Gif_5.setObjectName("Gif_5")
        self.Gif_6 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_6.setGeometry(QtCore.QRect(10, 630, 620, 300))
        self.Gif_6.setText("")
        self.Gif_6.setPixmap(QtGui.QPixmap("GUI-Gif/Health.gif"))
        self.Gif_6.setScaledContents(True)
        self.Gif_6.setObjectName("Gif_6")
        self.Gif_7 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_7.setGeometry(QtCore.QRect(1270, 630, 630, 310))
        self.Gif_7.setText("")
        self.Gif_7.setPixmap(QtGui.QPixmap("GUI-Gif/Code.gif"))
        self.Gif_7.setScaledContents(True)
        self.Gif_7.setObjectName("Gif_7")
        self.Gif_8 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_8.setGeometry(QtCore.QRect(640, 450, 620, 480))
        self.Gif_8.setText("")
        self.Gif_8.setPixmap(QtGui.QPixmap("GUI-Gif/Jarvis.gif"))
        self.Gif_8.setScaledContents(True)
        self.Gif_8.setObjectName("Gif_8")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(700, 900, 100, 30))
        self.Start.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.Start.setObjectName("Start")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(900, 900, 100, 30))
        self.Stop.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.Stop.setObjectName("Stop")
        self.Search = QtWidgets.QPushButton(self.centralwidget)
        self.Search.setGeometry(QtCore.QRect(1110, 900, 100, 30))
        self.Search.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.Search.setObjectName("Search")
        self.Text_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Date.setGeometry(QtCore.QRect(659, 480, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Text_Date.setFont(font)
        self.Text_Date.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 170, 255);\n"
"border: none;\n"
"")
        self.Text_Date.setObjectName("Text_Date")
        self.Text_Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Time.setGeometry(QtCore.QRect(670, 560, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Text_Time.setFont(font)
        self.Text_Time.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 170, 255);\n"
"border: none;\n"
"")
        self.Text_Time.setObjectName("Text_Time")
        self.Text_Temp = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Temp.setGeometry(QtCore.QRect(1039, 560, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Text_Temp.setFont(font)
        self.Text_Temp.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 170, 255);\n"
"border: none;\n"
"")
        self.Text_Temp.setObjectName("Text_Temp")
        self.Text_Day = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Day.setGeometry(QtCore.QRect(1039, 480, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Text_Day.setFont(font)
        self.Text_Day.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 170, 255);\n"
"border: none;\n"
"")
        self.Text_Day.setObjectName("Text_Day")
        IronManUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(IronManUI)
        QtCore.QMetaObject.connectSlotsByName(IronManUI)

    def retranslateUi(self, IronManUI):
        _translate = QtCore.QCoreApplication.translate
        IronManUI.setWindowTitle(_translate("IronManUI", "MainWindow"))
        self.Start.setText(_translate("IronManUI", "START"))
        self.Stop.setText(_translate("IronManUI", "STOP"))
        self.Search.setText(_translate("IronManUI", "SEARCH"))
        self.Text_Date.setHtml(_translate("IronManUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\"><br /></p></body></html>"))
        self.Text_Time.setHtml(_translate("IronManUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\"><br /></p></body></html>"))
        self.Text_Temp.setHtml(_translate("IronManUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\"><br /></p></body></html>"))
        self.Text_Day.setHtml(_translate("IronManUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IronManUI = QtWidgets.QMainWindow()
    ui = Ui_IronManUI()
    ui.setupUi(IronManUI)
    IronManUI.show()
    sys.exit(app.exec_())
