# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(1950, 950)
        self.centralwidget = QtWidgets.QWidget(JarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_1.setGeometry(QtCore.QRect(-110, -80, 2221, 1141))
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("GUI-Gif/Black_Template.jpg"))
        self.Bg_1.setScaledContents(True)
        self.Bg_1.setObjectName("Bg_1")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(10, 10, 610, 300))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("GUI-Gif/FullBodyScan.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(630, 10, 610, 300))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("GUI-Gif/ThreeD.jpg"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(1250, 10, 620, 300))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("GUI-Gif/World.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(10, 320, 610, 300))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("GUI-Gif/EMwave.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.Gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_5.setGeometry(QtCore.QRect(10, 630, 610, 300))
        self.Gif_5.setText("")
        self.Gif_5.setPixmap(QtGui.QPixmap("GUI-Gif/Health.gif"))
        self.Gif_5.setScaledContents(True)
        self.Gif_5.setObjectName("Gif_5")
        self.Gif_6 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_6.setGeometry(QtCore.QRect(1250, 630, 620, 300))
        self.Gif_6.setText("")
        self.Gif_6.setPixmap(QtGui.QPixmap("GUI-Gif/Code.gif"))
        self.Gif_6.setScaledContents(True)
        self.Gif_6.setObjectName("Gif_6")
        self.Gif_7 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_7.setGeometry(QtCore.QRect(1250, 320, 620, 300))
        self.Gif_7.setText("")
        self.Gif_7.setPixmap(QtGui.QPixmap("GUI-Gif/Search.gif"))
        self.Gif_7.setScaledContents(True)
        self.Gif_7.setObjectName("Gif_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(630, 320, 611, 581))
        self.textBrowser.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 170, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(830, 910, 91, 21))
        self.Start.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.Start.setObjectName("Start")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(950, 910, 91, 21))
        self.Exit.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.Exit.setObjectName("Exit")
        JarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))
        self.Start.setText(_translate("JarvisUI", "START"))
        self.Exit.setText(_translate("JarvisUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
